//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2.Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cenovnik_Putovanje
    {
        public int PutovanjeKojeNudiTuristickaAgencijaPutovanjeId { get; set; }
        public int PutovanjeKojeNudiTuristickaAgencijaTuristickaAgencijaId { get; set; }
        public int PutovanjeKojeNudiTuristickaAgencijaVodicId { get; set; }
        public int CenovnikKojiTuristickaAgencijaFormiraTuristickaAgencijaId { get; set; }
        public int CenovnikKojiTuristickaAgencijaFormiraCenovnikId { get; set; }
    
        public virtual PutovanjeKojeNudiTuristickaAgencija PutovanjeKojeNudiTuristickaAgencija { get; set; }
        public virtual CenovnikKojiTuristickaAgencijaFormira CenovnikKojiTuristickaAgencijaFormira { get; set; }
    }
}
