//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2.Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menadzer : Radnik
    {
        public int BrojPodredjenihRadnika { get; set; }
    
        public virtual Filijala Filijala1 { get; set; }
    }
}
