//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2.Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutovanjeKojeNudiTuristickaAgencija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PutovanjeKojeNudiTuristickaAgencija()
        {
            this.Ugovors = new HashSet<Ugovor>();
            this.Cenovnik_Putovanje = new HashSet<Cenovnik_Putovanje>();
        }
    
        public System.DateTime DatumDolaska { get; set; }
        public int Trajanje { get; set; }
        public double CenaPutovanja { get; set; }
        public string NazivSmestaja { get; set; }
        public int PutovanjeId { get; set; }
        public int TuristickaAgencijaId { get; set; }
        public int VodicId { get; set; }
    
        public virtual Putovanje Putovanje { get; set; }
        public virtual TuristickaAgencija TuristickaAgencija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ugovor> Ugovors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cenovnik_Putovanje> Cenovnik_Putovanje { get; set; }
        public virtual Vodic Vodic { get; set; }
    }
}
