//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2.Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuristickaAgencija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuristickaAgencija()
        {
            this.Filijalas = new HashSet<Filijala>();
            this.CenovnikKojiTuristickaAgencijaFormiras = new HashSet<CenovnikKojiTuristickaAgencijaFormira>();
            this.PutovanjeKojeNudiTuristickaAgencijas = new HashSet<PutovanjeKojeNudiTuristickaAgencija>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filijala> Filijalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenovnikKojiTuristickaAgencijaFormira> CenovnikKojiTuristickaAgencijaFormiras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutovanjeKojeNudiTuristickaAgencija> PutovanjeKojeNudiTuristickaAgencijas { get; set; }
    }
}
