//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2.Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugovor
    {
        public int Id { get; set; }
        public string SifraOsiguranja { get; set; }
        public int PutovanjeKojeNudiTuristickaAgencijaPutovanjeId { get; set; }
        public int PutovanjeKojeNudiTuristickaAgencijaTuristickaAgencijaId { get; set; }
        public int PutovanjeKojeNudiTuristickaAgencijaVodicId { get; set; }
        public int KlijentKojiPoslujeSaFilijalomKlijentId { get; set; }
        public int KlijentKojiPoslujeSaFilijalomFilijalaId { get; set; }
        public int KlijentKojiPoslujeSaFilijalomFilijalaTuristickaAgencijaId { get; set; }
        public int SekretaricaId { get; set; }
    
        public virtual PutovanjeKojeNudiTuristickaAgencija PutovanjeKojeNudiTuristickaAgencija { get; set; }
        public virtual KlijentKojiPoslujeSaFilijalom KlijentKojiPoslujeSaFilijalom { get; set; }
        public virtual Sekretarica Sekretarica { get; set; }
    }
}
